### ISSUE TITLE
Coverer.CellUnion(Point) can have multiple cells?

### ISSUE THREAD

**Issue by jsmorph** [golang/geo#58]
In S2, in some cases, a `Coverer.CellUnion()` of a `Point` can contain two cells. Is that the correct behavior? If so, what's the story?

Example:

```Go
package main

import (
	"fmt"

	"github.com/golang/geo/s2"
)

func main() {
	var (
		level   = 7
		coverer = s2.RegionCoverer{
			MinLevel: level,
			MaxLevel: level,
		}
		ll    = s2.LatLng{Lat: -0.8248776721189366, Lng: -2.038611228784389}
		p     = s2.PointFromLatLng(ll)
		union = coverer.CellUnion(p)
	)
	fmt.Println(len(union))
}

```

At the [playground](https://play.golang.org/p/tWqZ-jbLpZ9).

**Comment by jsmorph** [comment]
`5/0030111` and `5/0101000` both contain `s2.LatLng{Lat: -0.8248776721189366, Lng: -2.038611228784389}` per the [playground](https://play.golang.org/p/DKMl-pYCoea). Surprised me!

**Comment by rsned** [comment]
The RegionCoverer operates on Regions, and even though you are only using a
single Point, it is interpreted as a Region. The Coverer uses the
CellUnionBound() for the given Point which is a CellID slice of (top left,
top right, bottom left, bottom right) as the bounding box on the point at
the lowest level (30).

Even though the bounding box is microscopic, it does cross over the
boundary leading to it being in two cells at the same time.  You can see in
the attached images a view of the two level 7 cells with a tiny tiny tiny
spot.  Zooming in, the spot turns out to be the 4 cells.

fmt.Printf("%+v\n", p.CellUnionBound()):

  [5/01010003233230110323000103222 5/01010003233230110323000100111

   5/00301110322301001032333010333 5/00301110322301001032333011000]


You happened to get lucky (or unlucky) in that the LatLng you used happened
to be close enough to the edge of the two cells so that it's bounding box
spilled over.


-- Robert

**Comment by rsned** [comment]
![6eLhYruSp8U](https://user-images.githubusercontent.com/8549124/72854695-f05bc480-3c69-11ea-8e1c-4e11d566089b.png)
![KUY3ob5sLBe](https://user-images.githubusercontent.com/8549124/72854703-f651a580-3c69-11ea-9d91-d7cc15abf96a.png)

**Comment by jsmorph** [comment]
@rsned, thanks for the quick, detailed response.

For posterity:

Since `Cell.ContainsPoint(Point)` reports `true` for those two cells and that point, I decided actually read the [documentation](https://godoc.org/github.com/golang/geo/s2#Cell.ContainsPoint), which says to convert a `Cell` to a `Loop`. That [works](https://play.golang.org/p/_FRyNbN2bJ1).
