### ISSUE TITLE
NewClosestEdgeQuery problem

### ISSUE THREAD

**Issue by pshopper** [golang/geo#59]
Hello @rsned 

I use your golang package for finding the nearest polygon from geo point & i try to make it following this:

```golang
index := s2.NewShapeIndex()

// More than 4000 polygons of cities added to index
// ...

q := s2.NewClosestEdgeQuery(index, s2.NewClosestEdgeQueryOptions().MaxResults(1).IncludeInteriors(true))
target := s2.NewMinDistanceToPointTarget(s2.PointFromLatLng(s2.LatLngFromDegrees(40.853544, -73.099544)))
res := q.FindEdges(target)
```

I've got a problem, the method's implementation time is about 30 sec which is quite slow. 
Maybe i did smth wrong or it is an expected result?
if I exactly did smth wrong, could you please tell me how to realize it in a right way?

**Comment by rsned** [comment]
One thing that might assist in me debugging it is to get a sense of the
number of edges those thousands of cities ends up being.  Can you print
out  index.NumEdges()?  Is it in the 10's of thousands, millions, tens of
millions?

Is your slow time just the time on the Query, or does it include the
building of the ShapeIndex?

**Comment by pshopper** [comment]
Slow time is the time on the Query only. NumEdges is 429636.

**Comment by pshopper** [comment]
One thing that might assist in me debugging it is to get a sense of the
number of edges those thousands of cities ends up being.  Can you print
out  index.NumEdges()?  Is it in the 10's of thousands, millions, tens of
millions?

**Comment by pshopper** [comment]
Slow time is just the time on the Query. NumEdges is 429636.

**Comment by rsned** [comment]
OK, I tried it on a 5 million edge polygon, and the query took ~200 seconds to complete.

My guess is that the reason it's really slow with the large edge count is because so far, only the Brute Force implementation is done on it. See: https://github.com/golang/geo/blob/master/s2/edge_query.go#L466

It was the simplest of the code to port to get the code running

If you look at the original C++, the switch over point from brute force to optimized is set at ~100 edges.

https://github.com/google/s2geometry/blob/master/src/s2/s2closest_edge_query.cc#L46

Running the C++ benchmarks, optimized gains dramatically the larger the data inputs.

```
Benchmark             Time(ns) Optimized     Brute   Opt gain
-------------------------------------------------------------
BM_FindClosest<Fractal>/12          286        276     ~1x
BM_FindClosest<Fractal>/48          899        894     ~1x
BM_FindClosest<Fractal>/192        2077       3268     ~1.5x
BM_FindClosest<Fractal>/768        3679      12611     ~4x
BM_FindClosest<Fractal>/3k         6064      49593     ~8x
BM_FindClosest<Fractal>/12k        9068     195660    ~20x
BM_FindClosest<Fractal>/48k       12929     830409    ~60x
BM_FindClosest<Fractal>/192k      17310    3302094   ~190x
BM_FindClosest<Fractal>/768k      23289   13361211   ~575x
BM_FindClosest<Fractal>/3M        33153   58392773  ~1750x
``` 

So, while probably not quite as dramatic as the C++, the Go optimized implementation which should provide considerable savings once it's completed.  I don't have a specific ETA on when it will be completed, but I am still working through the porting to get it completed.
